// @flow

export const PAST_ACTIVITIES_REQUEST: string = 'GET_PAST_ACTIVITIES_REQUEST';
export const PAST_ACTIVITIES_ERROR: string = 'PAST_ACTIVITIES_ERROR';
export const GET_PAST_ACTIVITIES_SUCCESS: string = 'GET_PAST_ACTIVITIES_SUCCESS';
export const GET_PAST_ACTIVITIES_SUCCESS_FIRST_REQUEST: string = 'GET_PAST_ACTIVITIES_SUCCESS_FIRST_REQUEST';
export const GET_PAST_ACTIVITIES_CONTACTS_SUCCESS: string = 'GET_PAST_ACTIVITIES_CONTACTS_SUCCESS';
export const UPDATE_PAST_ACTIVITIES_SUCCESS: string = 'UPDATE_PAST_ACTIVITIES_SUCCESS';
export const GET_PAST_ACTIVITIES_COUNT_SUCCESS: string = 'GET_PAST_ACTIVITIES_COUNT_SUCCESS';
