// @flow

export const SET_TABLE_ACTIVITY_DATA: string = 'ACTIVITIES.SET_TABLE_ACTIVITY_DATA';
export const CREATE_TABLE_ACTIVITY: string = 'ACTIVITIES.CREATE_TABLE_ACTIVITY';
export const UPDATE_TABLE_ACTIVITY: string = 'ACTIVITIES.UPDATE_TABLE_ACTIVITY';
export const TABLE_ACTIVITY_SPINNER_ON: string = 'ACTIVITIES.TABLE_ACTIVITY_SPINNER_ON';
export const TABLE_ACTIVITY_SPINNER_OFF: string = 'ACTIVITIES.TABLE_ACTIVITY_SPINNER_OFF';
export const TABLE_ACTIVITY_ERROR: string = 'ACTIVITIES.TABLE_ACTIVITY_ERROR';
export const SET_FILTERS: string = 'ACTIVITIES.SET_FILTERS';
