/* eslint-disable symbol-description */
// @flow
export const RESUME_FETCHING = 'RESUME_FETCHING';
export const RESUME_FETCHING_SUCCESS = 'RESUME_FETCHING_SUCCESS';
export const RESUME_UPDATE_DATA = 'RESUME_UPDATE_DATA';
export const RESUME_UPDATE_DATA_FAIL = 'RESUME_UPDATE_DATA_FAIL';
export const RESUME_FETCHING_FAIL = 'RESUME_FETCHING_FAIL';
export const RESUME_SEND_COMMENT = 'RESUME_SEND_COMMENT';
export const RESUME_MARK_COMMENT_AS_SEEN = 'RESUME_MARK_COMMENT_AS_SEEN';
