// @flow

export const GET_TABLE_ESTIMATES_OF_PROJECTS: string = 'GET_TABLE_ESTIMATES_OF_PROJECTS';
export const GET_MORE_ESTIMATES_OF_PROJECTS: string = 'GET_MORE_ESTIMATES_OF_PROJECTS';
export const ERROR_DOWNLOAD_ESTIMATES_OF_PROJECTS: string = 'ERROR_DOWNLOAD_ESTIMATES_OF_PROJECTS';
