// @flow

export const ACTION = {
    ACTIVITIES_SUCCESS: 'GET_ACTIVITIES_SUCCESS',
    ACTIVITIES_ERROR: 'GET_ACTIVITIES_ERROR',
    ACTIVITIES_LOADING: 'GET_ACTIVITIES_LOADING',
    RESET_ACTIVITIES: 'RESET_STORE_ACTIVITIES',
    ACTIVITIES_RESPONSIBLE: 'SET_ACTIVITIES_RESPONSIBLE',
    SET_ACTIVITIES_DATE: 'SET_DATE_RANGE',
    SET_ACTIVITIES_SEARCH: 'SET_SEARCH_VALUE',
};

export const SALES_LINK = '/sales/';
